# Generated by Django 5.2.14 on 2026-05-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('toxicity', models.CharField(choices=[('Yenen', 'Yenen (Edible)'), ('Zehirli', 'Zehirli (Toxic)'), ('Ölümcül', 'Ölümcül (Deadly)')], max_length=20)),
                ('habitat', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mushroom_name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('confidence', models.FloatField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('mushroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='api.mushroom')),
            ],
        ),
    ]
