# Generated by Django 5.2.14 on 2026-05-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
